---
collections:
  - name: jchristianh.basos
    source: https://github.com/jchristianh-ansible-collections/baseos.git
    type: git
    version: main


  - name: community.general
    source: https://galaxy.ansible.com


...
