---
collections:
  # Our Collections
  - name: jchristianh.basos
    source: https://github.com/jchristianh-ansible-collections/baseos.git
    type: git
    version: main

  # External Collections
  - name: community.general
  - name: ansible.posix


...
