# CENTOS 9
#########################
---
kind: pipeline
type: docker
name: CentOS_9-Ansible-Pipeline

environment:
  ANSIBLE_INVENTORY : "-i 127.0.0.1, --connection=local"
  ANSIBLE_PLAYBOOK  : baseos.yml

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: "ansible_environment_verify"
    image: gitea.thezengarden.net/podman/ansible-dev/centos9:release
    commands:
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: "ansible_galaxy_requirements"
    image: gitea.thezengarden.net/podman/ansible-dev/centos9:release
    commands:
      - ansible-galaxy install -r requirements.yml

  - name: "ansible_lint"
    image: gitea.thezengarden.net/podman/ansible-dev/centos9:release
    commands:
      - ansible-lint --offline --exclude collections/ansible_collections --exclude .gitea

  - name: "ansible_playbook_execution"
    image: gitea.thezengarden.net/podman/ansible-dev/centos9:release
    commands:
      - ansible-playbook -v $ANSIBLE_INVENTORY $ANSIBLE_PLAYBOOK


# FEDORA 39
#########################
---
kind: pipeline
type: docker
name: Fedora_39-Ansible-Pipeline

environment:
  ANSIBLE_INVENTORY : "-i 127.0.0.1, --connection=local"
  ANSIBLE_PLAYBOOK  : baseos.yml

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: "ansible_environment_verify"
    image: gitea.thezengarden.net/podman/ansible-dev/fedora39:release
    commands:
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: "ansible_galaxy_requirements"
    image: gitea.thezengarden.net/podman/ansible-dev/fedora39:release
    commands:
      - ansible-galaxy install -r requirements.yml

  - name: "ansible_lint"
    image: gitea.thezengarden.net/podman/ansible-dev/fedora39:release
    commands:
      - ansible-lint --offline --exclude collections/ansible_collections --exclude .gitea

  - name: "ansible_playbook_execution"
    image: gitea.thezengarden.net/podman/ansible-dev/fedora39:release
    commands:
      - ansible-playbook -v $ANSIBLE_INVENTORY $ANSIBLE_PLAYBOOK


# DEBIAN 11
#########################
---
kind: pipeline
type: docker
name: Debian_11-Ansible-Pipeline

environment:
  ANSIBLE_INVENTORY : "-i 127.0.0.1, --connection=local"
  ANSIBLE_PLAYBOOK  : baseos.yml

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: "ansible_environment_verify"
    image: gitea.thezengarden.net/podman/ansible-dev/debian11:release
    commands:
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: "ansible_galaxy_requirements"
    image: gitea.thezengarden.net/podman/ansible-dev/debian11:release
    commands:
      - ansible-galaxy install -r requirements.yml

  - name: "ansible_lint"
    image: gitea.thezengarden.net/podman/ansible-dev/debian11:release
    commands:
      - ansible-lint --offline --exclude collections/ansible_collections --exclude .gitea

  - name: "ansible_playbook_execution"
    image: gitea.thezengarden.net/podman/ansible-dev/debian11:release
    commands:
      - ansible-playbook -v $ANSIBLE_INVENTORY $ANSIBLE_PLAYBOOK


# DEBIAN 12
#########################
---
kind: pipeline
type: docker
name: Debian_12-Ansible-Pipeline

environment:
  ANSIBLE_INVENTORY : "-i 127.0.0.1, --connection=local"
  ANSIBLE_PLAYBOOK  : baseos.yml

trigger:
  branch:
    exclude:
      - main
  event: [push]

steps:
  - name: "ansible_environment_verify"
    image: gitea.thezengarden.net/podman/ansible-dev/debian12:release
    commands:
      - git log -1
      - ansible --version
      - ansible-lint --version

  - name: "ansible_galaxy_requirements"
    image: gitea.thezengarden.net/podman/ansible-dev/debian12:release
    commands:
      - ansible-galaxy install -r requirements.yml

  - name: "ansible_lint"
    image: gitea.thezengarden.net/podman/ansible-dev/debian12:release
    commands:
      - ansible-lint --offline --exclude collections/ansible_collections --exclude .gitea

  - name: "ansible_playbook_execution"
    image: gitea.thezengarden.net/podman/ansible-dev/debian12:release
    commands:
      - ansible-playbook -v $ANSIBLE_INVENTORY $ANSIBLE_PLAYBOOK
