---
- name: Deploy a standardized configuration to target hosts
  hosts: all
  become: true
  gather_facts: true


  vars_files:
    - vars/baseos_vars.yml


  tasks:
    - name: Include defined role(s)
      ansible.builtin.import_role:
        name: "{{ item }}"
      loop: "{{ baseos_include_roles }}"


...
