---
- name: Deploy a standardized base configuration
  hosts: all
  become: yes
  gather_facts: yes


  collections:
    - jchristianh.baseos


  vars_files:
    - vars/baseos_vars.yml


  tasks:
    - name: Include relevant role(s)
      include_role:
        name: "{{ item }}"
      loop: "{{ __baseos_include_roles }}"


...
