---
- name: Provisions hosts using the jchristianh.baseos Ansible collection
  hosts: all
  become: yes
  gather_facts: yes


  collections:
    - jchristianh.baseos


  vars_files:
    - vars/baseos_vars.yml


  tasks:
    - name: Include relevant role(s)
      include_role:
        name: "{{ item }}"
      loop: "{{ baseos_include_roles }}"


...
