---
- name: Deploy a standardized base configuration
  hosts: all
  become: true
  gather_facts: true


  vars_files:
    - vars/baseos_vars.yml


  tasks:
    - name: Include relevant role(s)
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ __baseos_include_roles }}"


...
