---
collections:
  # Local Collections
  - name: jchristianh.baseos
    source: https://gitea.thezengarden.net/ansible_collections/ansible-collection-baseos.git
    type: git
    version: 1.0.28

  # Galaxy Collections
  - name: community.general
    version: 8.4.0

  - name: ansible.posix
    version: 1.5.4

...
