---
collections:
  # Local Collections
  - name: jchristianh.baseos
    source: https://gitea.thezengarden.net/ansible_collections/ansible-collection-baseos.git
    type: git
    version: 1.0.23

  # Galaxy Collections
  - name: community.general
  - name: ansible.posix

...
