---
collections:
  # Our Collections
  - name: jchristianh.basos
    source: https://gitea.thezengarden.net/ansible_collections/ansible-collection-baseos.git
    type: git
    version: testing

  # Galaxy Collections
  - name: community.general
  - name: ansible.posix


...
