name: Ansible Code Pipeline
run-name: ${{ gitea.actor }} is running Ansible Code Pipeline
on:
  push:
    branches:
      - testing

jobs:
  Ansible-Development-Pipeline:
    strategy:
      matrix:
        os: [ ansible-dev-centos9, ansible-dev-fedora39, ansible-dev-debian11, ansible-dev-debian12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Ansible Environment Verify
        run: |
          git log -1
          ansible --version
          ansible-lint --version

      - name: Install Ansible Galaxy Dependencies
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Run Ansible-Lint
        run: |
          ansible-lint --offline \
            --exclude collections/ansible_collections/ansible* \
            --exclude collections/ansible_collections/community* \
            --exclude .gitea

      - name: Run Ansible-Playbook
        run: |
          ansible-playbook -v -i 127.0.0.1, --connection=local baseos.yml
